language: php
php:
  - 5.4
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - "wget http://selenium.googlecode.com/files/selenium-server-standalone-2.31.0.jar"
  - # give xvfb some time to start
  - #rackup  # start a Web server
  - #sleep 3 # give Web server some time to bind to sockets, etc
  - php -S localhost:8000 -t public/ &
script:
  - "java -jar selenium-server-standalone-2.31.0.jar -htmlSuite *firefox http://localhost:8000/ /home/travis/build/yandod/travis-ci-selenium-php/SeleniumTest/tests.html ./result"
