language: php
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - "wget http://selenium.googlecode.com/files/selenium-server-standalone-2.31.0.jar"
  - sleep 3 # give xvfb some time to start
  - #rackup  # start a Web server
  - #sleep 3 # give Web server some time to bind to sockets, etc
  - cd public; php -S localhost:8000 &
script:
  - "java -jar selenium-server-standalone-2.31.0.jar -htmlSuite http://localhost:8000/ `pwd`/SeleniumTest/tests.html"
